// Refreshes data.generated.js from public sources. Run from the repo root:
//
//   node src/artifacts/inflation-calc/update-data.mjs
//
// (Node ≥22 ignores proxy env vars by default; behind a proxy run with NODE_USE_ENV_PROXY=1.)
// Needs network access to fred.stlouisfed.org (BLS series are mirrored there) and
// raw.githubusercontent.com (The Economist's Big Mac index). No dependencies.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const FRED = (id) => `https://fred.stlouisfed.org/graph/fredgraph.csv?id=${id}`;
const BIGMAC = "https://raw.githubusercontent.com/TheEconomist/big-mac-data/master/output-data/big-mac-full-index.csv";

async function csv(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  return (await res.text()).trim().split("\n").slice(1).map((l) => l.split(","));
}

// FRED CSV -> [{ y, m, v }] (skips blanks/"." which FRED uses for missing months)
async function fred(id) {
  const rows = await csv(FRED(id));
  return rows
    .filter(([, v]) => v !== "" && v !== ".")
    .map(([d, v]) => ({ y: +d.slice(0, 4), m: +d.slice(5, 7), v: +v }));
}

const round = (n, d = 3) => Math.round(n * 10 ** d) / 10 ** d;

// Calendar-year average, only for years that have at least `min` readings. BLS skipped
// October 2025 (federal shutdown), so BLS series accept 11 of 12 months.
function annual(rows, { min = 10, decimals = 3 } = {}) {
  const by = {};
  for (const { y, v } of rows) (by[y] ??= []).push(v);
  const out = {};
  for (const [y, vs] of Object.entries(by)) {
    if (vs.length >= min) out[y] = round(vs.reduce((a, b) => a + b, 0) / vs.length, decimals);
  }
  return out;
}

function latest(rows, count = 1, decimals = 3) {
  const tail = rows.slice(-count);
  const last = tail[tail.length - 1];
  return {
    now: round(tail.reduce((a, r) => a + r.v, 0) / tail.length, decimals),
    asOf: `${last.y}-${String(last.m).padStart(2, "0")}`,
  };
}

const series = (rows, opts = {}) => ({ annual: annual(rows, opts), ...latest(rows, opts.avgLast ?? 1, opts.decimals ?? 3) });

const cpiRows = await fred("CPIAUCNS");
const cpiMonthly = {};
for (const { y, m, v } of cpiRows) (cpiMonthly[y] ??= Array(12).fill(null))[m - 1] = v;

const bigmacRows = (await csv(BIGMAC))
  .filter((r) => r[1] === "USA")
  .map((r) => ({ y: +r[0].slice(0, 4), m: +r[0].slice(5, 7), v: +r[6] }));

const out = {
  CPI_MONTHLY: cpiMonthly,
  SERIES: {
    eggs: series(await fred("APU0000708111"), { min: 11 }),
    bread: series(await fred("APU0000702111"), { min: 11 }),
    gas: series(await fred("APU000074714"), { min: 11 }),
    // Census median sales price of new houses; the latest month is noisy, so use a 3-month mean.
    home: series(await fred("MSPNHSUS"), { min: 12, decimals: 0, avgLast: 3 }),
    wage: series(await fred("FEDMINNFRWG"), { min: 12, decimals: 2 }),
    // Economist Big Mac index: 1-2 readings per year, so average whatever the year has.
    bigmac: series(bigmacRows, { min: 1, decimals: 2 }),
    // Indices (not prices): scaled against known price anchors in data.js.
    rentIdx: series(await fred("CUUR0000SEHA"), { min: 11 }),
    movieIdx: series(await fred("CUUR0000SS62031"), { min: 11 }),
  },
};

const stamp = new Date().toISOString().slice(0, 10);
const body = [
  "// AUTO-GENERATED by update-data.mjs — do not edit by hand.",
  `export const GENERATED_AT = ${JSON.stringify(stamp)};`,
  `export const CPI_MONTHLY = ${JSON.stringify(out.CPI_MONTHLY)};`,
  `export const SERIES = ${JSON.stringify(out.SERIES, null, 1).replace(/\n\s*/g, " ")};`,
  "",
].join("\n");

const target = fileURLToPath(new URL("./data.generated.js", import.meta.url));
writeFileSync(target, body);
console.log(`wrote ${target} (${body.length} bytes)`);
for (const [k, s] of Object.entries(out.SERIES)) console.log(k.padEnd(8), `now=${s.now} (${s.asOf})`, `years=${Object.keys(s.annual).length}`);
